### ISSUE TITLE
Support for emacs 21 themes

### ISSUE THREAD

**Issue by Jimmysit0** [QuietTheme/Emacs#1]

**Comment by MCotocel** [comment]
I'll try and work on this over the next few days

**Comment by FrenzyExists** [comment]
[whats 21 te](https://github.com/emacs-jp/replace-colorthemes/blob/master/emacs-21-theme.el)
so this is emacs 21 themes...

**Comment by FrenzyExists** [comment]
btw @MCotocel is there any prob with me using the structure of your emacs theme (how is formatted) for aquarium?

**Comment by MCotocel** [comment]
> btw @MCotocel is there any prob with me using the structure of your emacs theme (how is formatted) for aquarium?

Not a problem, it's taken from doom-themes anyway. Just make sure to mention that doom-themes has to be installed

**Comment by MCotocel** [comment]
And about this issue, I'm not sure if I should make an emacs 21 theme. Last release of emacs 21 was in 2005.

**Comment by FrenzyExists** [comment]
> > btw @MCotocel is there any prob with me using the structure of your emacs theme (how is formatted) for aquarium?
> 
> Not a problem, it's taken from doom-themes anyway. Just make sure to mention that doom-themes has to be installed

No prob! Thanks :+1:

**Comment by Jimmysit0** [comment]
> And about this issue, I'm not sure if I should make an emacs 21 theme. Last release of emacs 21 was in 2005.

Sadly, I have to agree. :despair:
